[package]
name = "{{ project_name }}"
version = "0.1.0"
edition = "2024"
publish = false
resolver = "3"

[dependencies]
picodata-plugin = "25.1.1"
serde = { version = "1", features = ["derive"] }
log = "0.4"

[dev-dependencies]
picodata-pike = "2.0.0"
reqwest = { version = "0.12", features = ["blocking"] }

[build-dependencies]
picodata-pike = "2.0.0"
liquid = "0.26"
fs_extra = "1"

[lib]
crate-type = ["cdylib"]
