[package]
name = "{{ project_name }}"
version = "0.1.0"
edition = "2024"
publish = false
resolver = "3"

[dependencies]
picodata-plugin = "25.1.1"
serde = { version = "1", features = ["derive"] }
log = "0.4"
anyhow = "1.0.98"
once_cell = "1.21.3"
rmpv = "1.0.0"
tokio = "1.29.1"
shors = "0.12.3"
rmp-serde = "1.0.0"

[dev-dependencies]
picotest = "1.2.0"
rstest = "0.25.0"
reqwest = { version = "0.12", features = ["blocking"] }

[build-dependencies]
picodata-pike = "2.4.0"

[lib]
crate-type = ["cdylib"]
