[package]
name = "{{ project_name }}"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
picodata-plugin = "24.6.1"
serde = { version = "1", features = ["derive"] }
log = "0.4"

[dev-dependencies]
picodata-pike = { git = "https://github.com/picodata/pike.git", branch = "more_versions" } # TODO: change after publish on crates.io
reqwest = { version = "0.12", features = ["blocking"] }

[build-dependencies]
picodata-pike = { git = "https://github.com/picodata/pike.git", branch = "more_versions" } # TODO: change after publish on crates.io
liquid = "0.26"
fs_extra = "1"

[lib]
crate-type = ["cdylib"]
