[package]
name = "{{ project_name }}"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
picodata-plugin = "24.6.1"

[build-dependencies]
liquid = "0.26"
fs_extra = "1"

[lib]
crate-type = ["cdylib"]
