[tiers.default]
instances = 2
replication_factor = 2

[[tiers.default.services]]
name = "main"
plugin = "{{ project_name }}"
migration_envs = [
    { name = "example_name", value = "example_value" },
]
