[tier.default]
replicasets = 2
replication_factor = 2

[[tier.default.services]]
name = "main"
plugin = "{{ project_name }}"
migration_envs = [
    { name = "example_name", value = "example_value" },
]
