[tier.default]
replicasets = 2
replication_factor = 2

[plugin.{{ project_name }}]
migration_context = [
    { name = "example_name", value = "example_value" },
]

[plugin.{{ project_name }}.service.main]
tiers = ["default"]
