name: Release

on:
  release:
    types: [released]

jobs:
  release-crate:
    name: release crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.81.0"
      - run: cargo publish --locked --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
