name: Release

on:
  release:
    types: [released]

jobs:
  release-crate:
    name: release crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.85"
          components: clippy, rustfmt
      - run: cargo publish --locked --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

  bender-notify:
    name: bender notify
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{"parse_mode": "markdown", "text": "Good news, everyone!\nWe have another perfect release of Pike! *${{ github.event.release.tag_name }}*\nOh wait, that’s not my line…\n\nhttps://github.com/picodata/pike"}' \
            'https://api.telegram.org/bot${{ secrets.BENDER_TOKEN }}/sendMessage?chat_id=${{ secrets.NOTIFICATION_GROUP }}'
