name: Release

on:
  release:
    types: [released]

jobs:
  release-crate:
    name: release crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.85"
          components: clippy, rustfmt
      - run: cargo publish --locked --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
